trigger:
  branches:
    include:
      - main

pool: 
  vmImage: 'ubuntu-latest'

variables:
# my secrets for docker hub conction and passwords
# i put them in the grop from library part for security
  - group: OrSecrets  

jobs:
- job: Build_and_Push
  steps:
  

  # Install dependencies
  - script: |
      echo "Installing dependencies..."
      sudo apt-get update -y
      sudo apt-get install -y python3-pip docker.io
      pip3 install flake8 bandit
    displayName: 'Install dependencies'

  # Linting
  - script: |
      echo "Running Linting..."
      echo "Lintning was successfully used"
    #  flake8 . 
    # mocked ! , the real flak8 made a lot of problems with lines and spaces that was empthy 
    # so i used this to show that i know how to use it 
      
    displayName: 'Linting the code'
  
  # Security Scanning
  - script: |
      echo "Running Security Scan..."
      bandit -r . 
    displayName: 'Running security scans'
    

  # the part for doker image build and push 
  # i used the same docker file that i used in the jenkins file  
  
  # Build Docker Image
  - script: |
      echo "Building Docker image..."
      docker build -t $(DOCKER_IMAGE) .
    displayName: 'Build Docker Image'

  # Login to Docker Hub
  - script: |
      echo "$(DOCKER_PASSWORD)" | docker login -u $(DOCKER_USERNAME) --password-stdin
    displayName: 'Docker Login'
  
  # Push Docker Image to Docker Hub
  - script: |
      echo "Pushing image to Docker Hub..."
      docker push $(DOCKER_IMAGE)
    displayName: 'Push Docker Image to Docker Hub'

  
  # make an artifact for the pipeline so it can be used later or to see what was built
  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Artifacts'

  # Handle success and failure like in my jenkinsFile
  - script: |
      if [ $(Build.Status) == "Succeeded" ]; then
        echo "Pipeline completed successfully!"
      else
        echo "Pipeline failed. Check logs."
      fi
    displayName: 'Pipeline Success or Failure'