apiVersion: apps/v1
kind: Deployment
metadata:
  name: or-deployment
  labels:
    app: or
spec:
  replicas: 1
  selector:
    matchLabels:
      app: or
  template:
    metadata:
      labels:
        app: or
    spec:
      containers:
        - name: or-container
          image: orbiton3005/my-image:latest
          ports:
            - containerPort: 5001
            ### secrets stored in a saprate file could aws-credentials.env 
            ### file that is in the gitignore file
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-aws-secret
                  key: AWS_SECRET_ACCESS_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: or-service
spec:
  selector:
    app: or
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
