apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-aws-monitor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-aws-monitor
                port:
                  number: 5001
