apiVersion: v1
kind: Service
metadata:
  name: flask-aws-monitor
spec:
  selector:
    app: flask-aws-monitor
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: {{ .Values.service.type }}
